### ISSUE TITLE
HTML in `<title>` is being executed

### ISSUE THREAD

**Issue by webbower** [nickvdp/RecentTabList#10]
I had the following page open in Safari: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

It's `<title>` is: `<input> - HTML | MDN`

After the tab was closed, I happened to look at the popup of closed tabs for this plugin and saw this (screenshot attached)

![Recently Closed Tabs with HTML](https://cloud.githubusercontent.com/assets/602913/21123071/42d81a82-c08b-11e6-89b2-596572a08a31.png)

That's a live `<input>` element in the list.

**Comment by nickvdp** [comment]
Huh. That's no good at all. I'll do something about it. Thanks for reporting!

**Comment by nickvdp** [comment]
Fixed it. Will submit the update to Apple in a second. I've also added the .safariextz file to the repo, which should allow you to install this new version without waiting for Apple to update the gallery site (if you'd like).
