### ISSUE TITLE
keyboard shortcut?

### ISSUE THREAD

**Issue by gitjoost** [nickvdp/RecentTabList#12]
Very handy little extension, particular the search feature. Any chance you can add a keyboard shortcut to open 'Recent Tabs' so I can keep my hands on the keyboard?

**Comment by nickvdp** [comment]
Hey! I'd love to, but unfortunately it's not really possible (explained it in #1 and #4). Sorry :|

**Comment by gitjoost** [comment]
Hey Nick thanks for the reply. Have you ever seen the DEVON Think plugin?
They have a shortcut, see here:

Works well, never fails, no issues. Seems this _is_ possible?

-- 
joost

On May 15, 2017 at 8:07:02 PM, Nick van der Ploeg (notifications@github.com)
wrote:

Hey! I'd love to, but unfortunately it's not really possible (explained it
in #1 <https://github.com/nickvdp/RecentTabList/issues/1> and #4
<https://github.com/nickvdp/RecentTabList/issues/4>). Sorry :|

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nickvdp/RecentTabList/issues/12#issuecomment-301662890>,
or mute the thread

**Comment by nickvdp** [comment]
Yeah, looks like you can inject Javascript into the page to catch keyboard shortcuts and react to them. I looked into adding this, and unfortunately there's another roadblock after that. The popover (the menu that the entire extension resides in) can only be opened by a click, and cannot be opened programmatically through Javascript. 

Here's the documentation for the SafariExtensionPopover class. There's a hide() method but no show() method or anything like that.

https://developer.apple.com/documentation/safariextensions/safariextensionpopover

The Devonthink extension runs some Javascript to change the URL to a x-devonthink:// link, which is handled by their app.

**Comment by gitjoost** [comment]
Ah bummer, thanks for looking into this Nick!

**Comment by gingerbeardman** [comment]
Here's my solution to the hotkey problem, which uses Alfred to capture the Hotkey and AppleScript to click the Toolbar Button.

https://github.com/nickvdp/RecentTabList/issues/13#issuecomment-395111542

**Comment by gitjoost** [comment]
Hey ho, that’s a good one!  I could have figured this out myself (being a frequent user of Alfred). Thanks for the follow up after all this time!

- joost -

**Comment by nickvdp** [comment]
thanks @gingerbeardman! looks like a good solution. I'll look into your other suggestions soon.
