### ISSUE TITLE
Shows tabs in Private Windows, even after Window has been closed

### ISSUE THREAD

**Issue by james-rose** [nickvdp/RecentTabList#2]
Is it possible to either not show tabs from private windows, make it optional, or to stop showing the tabs in the list once that private window has been closed?  Otherwise it defeats the purpose of a private window.

**Comment by nickvdp** [comment]
Good question. I will look into that sometime soon.

Thanks.

**Comment by nickvdp** [comment]
Fixed a while back with https://github.com/nickvdp/RecentTabList/commit/a41857ee89f6dcd0d945aa9fb847494740d8f288

**Comment by jasontate** [comment]
<img width="546" alt="screen shot 2016-07-19 at 11 20 52 am" src="https://cloud.githubusercontent.com/assets/7143532/16961562/f080f5fc-4da2-11e6-97c7-78b42a2aefdc.png">
<img width="859" alt="screen shot 2016-07-19 at 11 20 59 am" src="https://cloud.githubusercontent.com/assets/7143532/16961564/f09eacdc-4da2-11e6-97ae-44ad20c651e8.png">

Unfortunately it didn't seem to work. 😢
