### ISSUE TITLE
Define a shortcut to open menu

### ISSUE THREAD

**Issue by ibr** [nickvdp/RecentTabList#4]
It would be nice to have use the keyboard to open the menu

**Comment by nickvdp** [comment]
I agree. It would be a great feature. Unfortunately, it's not possible with the Safari API. (I explain it a little more here: https://github.com/nickvdp/RecentTabList/issues/1#issuecomment-73421840)

**Comment by gingerbeardman** [comment]
Here's my solution to the hotkey problem, which uses Alfred to capture the Hotkey and AppleScript to click the Toolbar Button.

https://github.com/nickvdp/RecentTabList/issues/13#issuecomment-395111542
