### ISSUE TITLE
Show the url of the tab and style it a bit more closely as in iOS Safari

### ISSUE THREAD

**Issue by nuno-agostinho** [nickvdp/RecentTabList#5]
The Safari in iOS shows each closed tabs' title and URL separated with a horizontal bar. That allows to show more information in a prettier format. Another thing that could be included could be favicons OR (even better since they are scalable images) the Pinned Tab Icons.

![img_0405](https://cloud.githubusercontent.com/assets/3199157/13547843/49170d08-e2d9-11e5-9db8-fc920dab2352.jpg)

**Comment by nickvdp** [comment]
Good idea. I'll consider re-styling it. That said, I think the Pinned Tab icons and favicons aren't directly accessible through the Safari extension API so those will be tough to add. The extension used to support favicons using a web service, but it started charging so I dropped the feature.

**Comment by nickvdp** [comment]
Took me a while, but I added an option to show the URL. Didn't add the lines, but it's actually pretty easy to see the separation without them.
