### ISSUE TITLE
Doesn't seem to adhere to the # of recent tabs preference

### ISSUE THREAD

**Issue by jasontate** [nickvdp/RecentTabList#6]
Using Safari 9.1, and version 1.2.2 of the extension, when selecting in the preferences setting the "number of recent tabs" — the menu shows way, way more. I've got 5 selected here in preferences and as you can see it's grown over the day to be massive.

<img width="545" alt="screen shot 2016-05-17 at 3 19 16 pm" src="https://cloud.githubusercontent.com/assets/7143532/15341317/cdb8dfc6-1c42-11e6-9a52-e83df0bc8286.png">

**Comment by nickvdp** [comment]
Weird! Thanks for reporting it, I'll take a look at the code and see if I can figure it out.

**Comment by nickvdp** [comment]
This should make things more reliable: https://github.com/nickvdp/RecentTabList/commit/fa4573f379908d603b1b3d51ac24cb03780bcc44
